image:
  repository: antohachaban
  name: messaging-service
  tag: latest

migrations:
  image:
    repository: antohachaban
    name: service-migrations
    tag: latest
  config:
    POSTGRESQL_URL: "postgres://admin:admin@postgres:5432/linkshortener?sslmode=disable"
    VERSION: "000001"

configs:
  POSTGRES_DB: linkshortener
  POSTGRES_HOST: postgres:5432
  RABBITMQ_HOST: "rabbitmq"

secrets:
  POSTGRES_USER: "YWRtaW4=" # admin
  POSTGRES_PASSWORD: "YWRtaW4=" # admin
  RABBITMQ_USER: "Z3Vlc3Q=" #guest
  RABBITMQ_PASSWORD: "Z3Vlc3Q=" #guest

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /api/messages
  port: http