apiVersion: v2
type: application
version: 0.0.1
name: user-service
appVersion: "0.1"
description: "user service helm"
dependencies:
  - name: common
    version: 0.1.0
    repository: file://../common