apiVersion: v2
type: application
version: 0.0.3
name: demo-helm
appVersion: "0.1"
description: "demo"
dependencies:
- name: postgresql
  version: 12.2.7
  repository: https://charts.bitnami.com/bitnami
- name: common
  version: 0.1.0
  repository: file://charts/common
- name: rabbitmq
  version: 11.14.3
  repository: https://charts.bitnami.com/bitnami  